InlayHints:
  Enabled: false
  BlockEnd: false
  Designators: true
  ParameterNames: true
  DeducedTypes: true
  DefaultArguments: false
  TypeNameLimit: 24

Diagnostics:
  Suppress: [-Wformat, -Wunused]
